version: '3.8'

services:
  db:
    image: postgres:13.1
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: database_development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ../data/db-data:/var/lib/postgresql/data
    networks:
      - booster-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  booster-net:
    driver: bridge
